name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Sample app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
                    
          script: |             
            cd /var/www/html/           
            git clone git@github.com:pojiepoj/lab_exercise.git .
            echo 'Deployment successful to digital ocean' 
